### ISSUE TITLE
Cancel button (top left) not working, payment listeners not firing

### ISSUE THREAD

**Issue by ericpolkadoc** [hansemannn/ti.paypal#3] opened 2016-08-24 17:45 UTC
Hi there,

Working with your module this morning, having a few issues.
-  Cancel button does not close anything, or seem to affect anything.  I was expecting it to close the Paypal modal window.

-- Payments work, however the event is the payment.addEventListeners don't seem to be catching anything -- i have some simple console.logs as well as your Ti.API.warn's in there.  

-- What would be the method to close the PP modal in one of the event listeners?

Thanks!

**Comment by yozef** [comment] 2016-08-24 17:47
This is a duplicate of [issue #2 ](https://github.com/hansemannn/ti.paypal/issues/2)

**Comment by ericpolkadoc** [comment] 2016-08-24 17:52
Hi,

Yes this is duplicate.  Has there been a fix for the issue(s)?   I am using the latest master that is referenced in #2.

This is a nice module, would love to be able to use it.

Thanks!

**Comment by hansemannn** [comment] 2016-08-24 22:30
Please watch the other issue, thanks!

**Closed as completed by hansemannn** 2016-08-24 22:30 UTC

**Comment by ericpolkadoc** [comment] 2016-08-25 17:30
Looks like things are working now -- awesome and thanks!

**Comment by hansemannn** [comment] 2016-08-26 21:31
Good to know, thanks!
